server:
  port: 9001

spring:
  application:
    name: microservice-user 
  datasource:
    url: jdbc:mysql://localhost:3308/MicroServiceUser?characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
    generate-ddl: true
    database: mysql
